# Test ubuntu pod and volumes for troubleshooting
apiVersion: v1
kind: PersistentVolume
metadata:
  name: ubuntu-debug-data
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 1Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: ubuntu-debug-data
    namespace: default
  nfs:
    path: /mnt/nas/data
    server: truenas.lab.kevinf.xyz
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  volumeMode: Filesystem

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: ubuntu-debug-files
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 1Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: ubuntu-debug-files
    namespace: default
  nfs:
    path: /mnt/nas/files
    server: truenas.lab.kevinf.xyz
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  volumeMode: Filesystem

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ubuntu-debug-data
  namespace: default
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: ""
  volumeMode: Filesystem
  volumeName: ubuntu-debug-data

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ubuntu-debug-files
  namespace: default
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: ""
  volumeMode: Filesystem
  volumeName: ubuntu-debug-files

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ubuntu-debug
  namespace: default
  labels:
    app: ubuntu-debug
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ubuntu-debug
  template:
    metadata:
      labels:
        app: ubuntu-debug
    spec:
      containers:
      - name: ubuntu-debug
        image: kevinchanaka/ubuntu-user:latest
        volumeMounts:
        - name: data
          mountPath: /home/ubuntu/mount/data
        - name: files
          mountPath: /home/ubuntu/mount/files
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: ubuntu-debug-data
      - name: files
        persistentVolumeClaim:
          claimName: ubuntu-debug-files
