apiVersion: v2
name: kube-prometheus
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: "1.0"
dependencies:
- name: kube-prometheus
  version: 35.2.0
  repository: https://prometheus-community.github.io/helm-charts