apiVersion: v1
kind: ConfigMap
metadata:
  name: openldap
  namespace: auth
data:
  LDAP_ORGANISATION: "Home Lab"
  LDAP_DOMAIN: "kevinf.xyz"
  LDAP_TLS: "true"
  LDAP_TLS_ENFORCE: "true"
  LDAP_TLS_VERIFY_CLIENT: "never"
  LDAP_TLS_CRT_FILENAME: tls.crt
  LDAP_TLS_KEY_FILENAME: tls.key
  LDAP_TLS_CA_CRT_FILENAME: tls.crt

---

apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: openldap-tls
  namespace: auth
spec:
  secretName: openldap-tls
  dnsNames:
  - ldap.lab.kevinf.xyz
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: letsencrypt-prod
  usages:
  - digital signature
  - key encipherment

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: openldap
  namespace: auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: openldap
  template:
    metadata:
      labels:
        app: openldap
    spec:
      initContainers:
      - name: cert-copy
        image: ubuntu
        volumeMounts:
        - name: certs
          mountPath: /data/tmp
        - name: scratch
          mountPath: /data/certs
        command: ["/bin/bash"]
        args:
        - -c
        - >
          cp -rL /data/tmp/tls* /data/certs;
      containers:
      - name: openldap
        image: osixia/openldap:latest
        ports:
        - name: ldap
          containerPort: 389
        - name: ldaps
          containerPort: 636
        envFrom:
        - configMapRef: 
            name: openldap
        - secretRef:
            name: ldap-admin-password
        volumeMounts:
        - name: scratch
          mountPath: /container/service/slapd/assets/certs
          readOnly: false
        resources: 
          requests: 
            cpu: 200m
      volumes:
      - name: certs
        secret:
          secretName: openldap-tls
      - name: scratch
        emptyDir: {}
        
---

apiVersion: v1
kind: Service
metadata:
  name: openldap
  namespace: auth
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.50.163
  selector:
    app: openldap
  ports:
  - protocol: TCP
    name: ldap
    port: 389
