apiVersion: v1
kind: PersistentVolume
metadata:
  name: transmission
  namespace: default
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 1Gi
  claimRef:
    name: transmission
    namespace: default
  nfs:
    path: /mnt/NASPool/data/media/transmission
    server: freenas.local 

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: transmission
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  volumeName: transmission

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: transmission-home
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi

---

apiVersion: v1
kind: Secret
metadata:
  name: pia-vpn
  namespace: default
type: Opaque
data:
  username: "{{ vpn.username | b64encode }}"
  password: "{{ vpn.password | b64encode }}"

---

apiVersion: v1
kind: Secret
metadata:
  name: transmission
  namespace: default
type: Opaque
data:
  username: "{{ transmission.username | b64encode }}"
  password: "{{ transmission.password | b64encode }}"

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: transmission
  namespace: default
  labels:
    app: transmission
spec:
  replicas: 0
  selector:
    matchLabels:
      app: transmission
  template:
    metadata:
      labels:
        app: transmission
    spec:
      containers:
      - name: transmission
        image: haugene/transmission-openvpn
        ports:
        - containerPort: 9091
        securityContext:
          capabilities:
            add:
            - NET_ADMIN    
        env:
        - name: LOCAL_NETWORK
          value: 192.168.50.0/24
        - name: TRANSMISSION_WEB_UI
          value: flood-for-transmission
        - name: OPENVPN_PROVIDER
          value: PIA
        - name: OPENVPN_CONFIG
          value: au_sydney
        - name: OPENVPN_USERNAME
          valueFrom:
            secretKeyRef:
              name: pia-vpn
              key: username
        - name: OPENVPN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: pia-vpn
              key: password
        - name: WEBPROXY_ENABLED
          value: "true"
        - name: WEBPROXY_PORT
          value: "8888"
        - name: TRANSMISSION_HOME
          value: "/home/transmission-home/"
        - name: TRANSMISSION_RPC_AUTHENTICATION_REQUIRED
          value: "true"
        - name: TRANSMISSION_RPC_ENABLED
          value: "true"
        - name: TRANSMISSION_RPC_USERNAME
          valueFrom:
            secretKeyRef:
              name: transmission
              key: username
        - name: TRANSMISSION_RPC_PASSWORD
          valueFrom:
            secretKeyRef:
              name: transmission
              key: password
        volumeMounts:
        - name: data
          mountPath: /data
        - name: home
          mountPath: /home/transmission-home
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: transmission
      - name: home
        persistentVolumeClaim:
          claimName: transmission-home

---

apiVersion: v1
kind: Service
metadata:
  name: transmission
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: transmission
  ports:
    - protocol: TCP
      port: 9091

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: transmission
  namespace: default
  annotations:
    kubernetes.io/ingress.class: "nginx" 
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
  - hosts: 
    - transmission.lab.kevinf.xyz
    secretName: transmission-tls
  rules:
  - host: transmission.lab.kevinf.xyz
    http:
      paths:
      - backend:
          service:
            name: transmission
            port: 
              number: 9091
        path: /
        pathType: Prefix
