apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: terraria-daves
  namespace: default
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: terraria-daves
  namespace: default
  labels:
    app: terraria-daves
spec:
  replicas: 1
  selector:
    matchLabels:
      app: terraria-daves
  template:
    metadata:
      labels:
        app: terraria-daves
    spec:
      containers:
      - name: terraria
        image: kevinchanaka/terraria:latest
        ports:
        - containerPort: 7777
        volumeMounts:
        - name: data
          mountPath: /app/data
        - name: config
          mountPath: /app/data/config/serverconfig.txt
          subPath: serverconfig.txt
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: terraria-daves
      - name: config
        configMap:
          items:
          - key: serverconfig.txt
            path: serverconfig.txt
          name: terraria-daves
        
---

apiVersion: v1
kind: Service
metadata:
  name: terraria-daves
  namespace: default
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.50.163
  selector:
    app: terraria-daves
  ports:
    - protocol: TCP
      port: 7777

---

apiVersion: batch/v1
kind: CronJob
metadata:
  name: terraria-daves-restart
  namespace: default
spec:
  schedule: "30 3 * * *"
  timeZone: Australia/Sydney
  startingDeadlineSeconds: 300
  failedJobsHistoryLimit: 1
  successfulJobsHistoryLimit: 0
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: kubectl
            image: bitnami/kubectl
            env:
            - name: DEPLOYMENT_NAME
              value: terraria-daves
            command: ["/bin/bash"]
            args: ["/app/restart.sh"]
            volumeMounts:
            - name: script
              mountPath: /app
          volumes:
          - name: script
            configMap:
              name: scaler
          restartPolicy: OnFailure
          serviceAccountName: scaler
