apiVersion: v2
name: ingress-nginx
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: "1.0"
dependencies:
- name: ingress-nginx
  version: 4.4.2
  repository: https://kubernetes.github.io/ingress-nginx