# Values file for metallb https://github.com/metallb/metallb/tree/main/charts/metallb
# helm upgrade -i -n metallb-system -f metallb.yaml metallb metallb/metallb

metallb:
  crds:
    enabled: true

  controller:
    resources:
      requests:
        cpu: 25m
        memory: 25Mi

  speaker:
    resources:
      requests:
        cpu: 25m
        memory: 25Mi
