apiVersion: v2
name: loki
description: A Helm chart for Kubernetes
type: loki
version: 0.1.0
appVersion: "1.0"
dependencies:
- name: loki
  version: 3.8.1
  repository: https://grafana.github.io/helm-charts