apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
spec:
  project: default
  sources:
  - repoURL: https://charts.jetstack.io
    chart: cert-manager
    targetRevision: 1.14.4
    helm:
      releaseName: cert-manager
      valueFiles:
      - $repo/values/cert-manager.yaml
  - repoURL: https://github.com/kevinchanaka/kube-cluster-apps.git
    targetRevision: HEAD
    ref: repo
  destination:
    namespace: cert-manager
    server: https://kubernetes.default.svc

---

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb
  namespace: argocd
spec:
  project: default
  sources:
  - repoURL: https://metallb.github.io/metallb
    chart: metallb
    targetRevision: 0.14.4
    helm:
      releaseName: metallb
      valueFiles:
      - $repo/values/metallb.yaml
  - repoURL: https://github.com/kevinchanaka/kube-cluster-apps.git
    targetRevision: HEAD
    ref: repo
  destination:
    namespace: metallb-system
    server: https://kubernetes.default.svc
  ignoreDifferences:
  - group: "apiextensions.k8s.io"
    kind: CustomResourceDefinition
    name: bgppeers.metallb.io
    jsonPointers:
    - /spec/conversion/webhook/clientConfig/caBundle

---

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  namespace: argocd
spec:
  project: default
  sources:
  - repoURL: https://kubernetes.github.io/ingress-nginx
    chart: ingress-nginx
    targetRevision: 4.10.0
    helm:
      releaseName: ingress-nginx
      valueFiles:
      - $repo/values/ingress-nginx.yaml
  - repoURL: https://github.com/kevinchanaka/kube-cluster-apps.git
    targetRevision: HEAD
    ref: repo
  destination:
    namespace: ingress-nginx
    server: https://kubernetes.default.svc

---

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metrics-server
  namespace: argocd
spec:
  project: default
  sources:
  - repoURL: https://kubernetes-sigs.github.io/metrics-server/
    chart: metrics-server
    targetRevision: 3.12.1
    helm:
      releaseName: metrics-server
      valueFiles:
      - $repo/values/metrics-server.yaml
  - repoURL: https://github.com/kevinchanaka/kube-cluster-apps.git
    targetRevision: HEAD
    ref: repo
  destination:
    namespace: kube-system
    server: https://kubernetes.default.svc

---

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nfs-subdir-external-provisioner
  namespace: argocd
spec:
  project: default
  sources:
  - repoURL: https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner/
    chart: nfs-subdir-external-provisioner
    targetRevision: 4.0.18
    helm:
      releaseName: nfs-subdir-external-provisioner
      valueFiles:
      - $repo/values/nfs-provisioner.yaml
  - repoURL: https://github.com/kevinchanaka/kube-cluster-apps.git
    targetRevision: HEAD
    ref: repo
  destination:
    namespace: kube-system
    server: https://kubernetes.default.svc

---

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
spec:
  project: default
  sources:
  - repoURL: https://prometheus-community.github.io/helm-charts
    chart: kube-prometheus-stack
    targetRevision: 58.0.0
    helm:
      releaseName: kps
      skipCrds: true
      valueFiles:
      - $repo/values/kube-prometheus-stack.yaml
  - repoURL: https://github.com/kevinchanaka/kube-cluster-apps.git
    targetRevision: HEAD
    ref: repo
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc

---

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack-crds
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/prometheus-community/helm-charts.git
    path: charts/kube-prometheus-stack/charts/crds/crds
    targetRevision: kube-prometheus-stack-58.0.0
    directory:
      recurse: true
  syncPolicy:
    syncOptions:
    - Replace=true
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc

---

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: zfs-iscsi
  namespace: argocd
spec:
  project: default
  sources:
  - repoURL: https://democratic-csi.github.io/charts/
    chart: democratic-csi
    targetRevision: 0.14.6
    helm:
      releaseName: zfs-iscsi
      valueFiles:
      - $repo/values/zfs-iscsi.yaml
  - repoURL: https://github.com/kevinchanaka/kube-cluster-apps.git
    targetRevision: HEAD
    ref: repo
  destination:
    namespace: democratic-csi
    server: https://kubernetes.default.svc
