apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
spec:
  destination:
    namespace: cert-manager
    server: https://kubernetes.default.svc
  project: default
  source:
    path: charts/cert-manager
    repoURL: https://github.com/kevinchanaka/kube-cluster-apps.git
    targetRevision: HEAD

---

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb
  namespace: argocd
spec:
  destination:
    namespace: metallb-system
    server: https://kubernetes.default.svc
  project: default
  source:
    path: charts/metallb
    repoURL: https://github.com/kevinchanaka/kube-cluster-apps.git
    targetRevision: HEAD

---

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  namespace: argocd
spec:
  destination:
    namespace: ingress-nginx
    server: https://kubernetes.default.svc
  project: default
  source:
    path: charts/ingress-nginx
    repoURL: https://github.com/kevinchanaka/kube-cluster-apps.git
    targetRevision: HEAD

---

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metrics-server
  namespace: argocd
spec:
  destination:
    namespace: kube-system
    server: https://kubernetes.default.svc
  project: default
  source:
    path: charts/metrics-server
    repoURL: https://github.com/kevinchanaka/kube-cluster-apps.git
    targetRevision: HEAD

---

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nfs-subdir-external-provisioner
  namespace: argocd
spec:
  destination:
    namespace: kube-system
    server: https://kubernetes.default.svc
  project: default
  source:
    path: charts/nfs-provisioner
    repoURL: https://github.com/kevinchanaka/kube-cluster-apps.git
    targetRevision: HEAD

---

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus
  namespace: argocd
spec:
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  project: default
  source:
    path: charts/kube-prometheus
    repoURL: https://github.com/kevinchanaka/kube-cluster-apps.git
    targetRevision: HEAD

---

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: zfs-iscsi
  namespace: argocd
spec:
  destination:
    namespace: democratic-csi
    server: https://kubernetes.default.svc
  project: default
  source:
    path: charts/zfs-iscsi
    repoURL: https://github.com/kevinchanaka/kube-cluster-apps.git
    targetRevision: HEAD
