apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minecraft
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    path: manifests
    repoURL: git@github.com:kevinchanaka/kube-cluster-apps.git
    targetRevision: HEAD
    directory:
      include: "minecraft*.yaml"

---

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: home-assistant
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    path: manifests
    repoURL: git@github.com:kevinchanaka/kube-cluster-apps.git
    targetRevision: HEAD
    directory:
      include: "home-assistant.yaml"

---

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: plex
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    path: manifests
    repoURL: git@github.com:kevinchanaka/kube-cluster-apps.git
    targetRevision: HEAD
    directory:
      include: "plex.yaml"

---

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sagemcom-router-reboot
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    path: manifests
    repoURL: git@github.com:kevinchanaka/kube-cluster-apps.git
    targetRevision: HEAD
    directory:
      include: "sagemcom-router-reboot.yaml"

---

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: transmission
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    path: manifests
    repoURL: git@github.com:kevinchanaka/kube-cluster-apps.git
    targetRevision: HEAD
    directory:
      include: "transmission.yaml"

---

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: terraria-daves
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    path: manifests
    repoURL: git@github.com:kevinchanaka/kube-cluster-apps.git
    targetRevision: HEAD
    directory:
      include: "terraria-daves.yaml"

---

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: terraria-un-spacey
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    path: manifests
    repoURL: git@github.com:kevinchanaka/kube-cluster-apps.git
    targetRevision: HEAD
    directory:
      include: "terraria-un-spacey.yaml"

---

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: miscellaneous
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    path: manifests
    repoURL: git@github.com:kevinchanaka/kube-cluster-apps.git
    targetRevision: HEAD
    directory:
      include: "misc.yaml"
