apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: proxmox-csi-plugin
  namespace: csi-proxmox
spec:
  secretStoreRef:
    name: infisical
    kind: ClusterSecretStore 
  refreshPolicy: OnChange
  data:
    - secretKey: token
      remoteRef:
        key: proxmox-csi-token
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      data:
        config.yaml: |
          clusters:
          - url: https://pve.lab.kevinf.xyz/api2/json
            insecure: true
            token_id: "kubernetes-csi@pve!csi"
            token_secret: "{{ .token }}"
            region: pve

---

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: proxmox-data-ext4
parameters:
  csi.storage.k8s.io/fstype: ext4
  storage: local-lvm
  cache: none
  ssd: "true"
provisioner: csi.proxmox.sinextra.dev
allowVolumeExpansion: true
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
