# App to perform dynamic DNS via Cloudflare

apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflare-ddns
  namespace: default
data:
  API_ENDPOINT: https://api.cloudflare.com/client/v4
  ZONE_ID: ce0d4f1d277f698c1fc083c5732e1f4a
  DOMAIN: "mynetwork.kevinf.xyz"
  RULE_ID: "840aa0e2a5a77f86924893b62fcf16fe"

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflare-ddns-script
  namespace: default
data:
  cloudflare-ddns.sh: |
    #!/bin/bash
    
    function log() {
      echo "[`date`] $1"
    }

    while true; do
      DDNS_CURRENT_IP=`dig +short $DOMAIN`
      UPDATE_IP=`dig +short myip.opendns.com @resolver1.opendns.com`

      log "Current public IP is $UPDATE_IP"
      log "Public IP within DNS record is $DDNS_CURRENT_IP"      

      if [ "$DDNS_CURRENT_IP" != "$UPDATE_IP" ]; then
        log "Updating DNS record"

        curl --silent -X PUT "${API_ENDPOINT}/zones/${ZONE_ID}/dns_records/${RULE_ID}/" \
          -H "Content-Type:application/json" \
          -H "Authorization: Bearer ${API_TOKEN}" \
          --data '{"type":"A", "name":"'${DOMAIN}'", "content":"'${UPDATE_IP}'"}'
        echo

      else
        log "Public IP unchanged, skipping DNS record update"
      fi

      sleep 300
    done

---

apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare-api-ddns-token
  namespace: default
spec:
  secretStoreRef:
    name: kubernetes-eso
    kind: ClusterSecretStore
  refreshInterval: 1h
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: token
      remoteRef:
        key: app-secrets
        property: CLOUDFLARE_API_TOKEN

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflare-ddns
  namespace: default
  labels:
    app: cloudflare-ddns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudflare-ddns
  template:
    metadata:
      labels:
        app: cloudflare-ddns
    spec:
      containers:
      - name: ubuntu
        image: kevinchanaka/ubuntu-user:latest
        envFrom:
        - configMapRef:
            name: cloudflare-ddns
        env:
        - name: API_TOKEN
          valueFrom:
            secretKeyRef:
              name: cloudflare-api-ddns-token
              key: token
        command: ["/bin/bash"]
        args: ["/app/cloudflare-ddns.sh"]
        volumeMounts:
        - name: script
          mountPath: /app
      volumes:
      - name: script
        configMap:
          name: cloudflare-ddns-script
