# Values file for democratic-csi helm chart
# https://github.com/democratic-csi/charts/blob/master/stable/democratic-csi/values.yaml
# https://github.com/democratic-csi/democratic-csi/blob/master/examples/freenas-iscsi.yaml
# helm upgrade -i -n democratic-csi -f democratic-csi.yaml zfs-iscsi democratic-csi/democratic-csi

democratic-csi:
  csiDriver:
    name: "org.democratic-csi.iscsi"

  storageClasses:
  - name: truenas-iscsi-csi
    defaultClass: false
    reclaimPolicy: Retain
    volumeBindingMode: Immediate
    allowVolumeExpansion: true
    parameters:
      fsType: ext4

    mountOptions: []
    secrets:
      provisioner-secret:
      controller-publish-secret:
      node-stage-secret:
      node-publish-secret:
      controller-expand-secret:

  volumeSnapshotClasses: []

  driver:
    existingConfigSecret: zfs-iscsi-democratic-csi-driver-config
    config:
      driver: freenas-iscsi
