apiVersion: v2
name: metallb
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: "1.0"
dependencies:
- name: metallb
  version: 3.0.2
  repository: https://charts.bitnami.com/bitnami