# Values file for metallb https://github.com/bitnami/charts/tree/master/bitnami/metallb/
# helm upgrade -i -n metallb-system -f metallb.yaml metallb bitnami/metallb

metallb:
  configInline:
    address-pools:
    - name: default
      protocol: layer2
      addresses:
      - 192.168.50.160-192.168.50.170

  controller:
    resources:
      requests:
        cpu: 25m
        memory: 25Mi

  speaker:
    resources:
      requests:
        cpu: 25m
        memory: 25Mi
