apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  project: default
  sources:
  - repoURL: ghcr.io/argoproj/argo-helm
    chart: argo-cd
    targetRevision: "9.4.*"
    helm:
      releaseName: argocd
      valueFiles:
      - $repo/values/argocd.yaml
  - repoURL: https://github.com/kevinchanaka/kube-cluster-apps.git
    targetRevision: HEAD
    ref: repo
  syncPolicy:
    syncOptions:
    - ServerSideApply=true
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc

---

# Releases: https://github.com/kubernetes-sigs/metrics-server/releases?q=metrics-server-helm-chart&expanded=true
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: flannel
  namespace: argocd
spec:
  project: default
  sources:
  - repoURL: https://flannel-io.github.io/flannel/
    chart: flannel
    targetRevision: "v0.*"
    helm:
      releaseName: flannel
      valueFiles:
      - $repo/values/flannel.yaml
  - repoURL: https://github.com/kevinchanaka/kube-cluster-apps.git
    targetRevision: HEAD
    ref: repo
  syncPolicy:
    syncOptions:
    - ServerSideApply=true
  destination:
    namespace: kube-system
    server: https://kubernetes.default.svc

---

# Releases: https://github.com/kubernetes-sigs/metrics-server/releases?q=metrics-server-helm-chart&expanded=true
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metrics-server
  namespace: argocd
spec:
  project: default
  sources:
  - repoURL: https://kubernetes-sigs.github.io/metrics-server/
    chart: metrics-server
    targetRevision: "3.*"
    helm:
      releaseName: metrics-server
      valueFiles:
      - $repo/values/metrics-server.yaml
  - repoURL: https://github.com/kevinchanaka/kube-cluster-apps.git
    targetRevision: HEAD
    ref: repo
  destination:
    namespace: kube-system
    server: https://kubernetes.default.svc

---

# Releases: https://github.com/external-secrets/external-secrets/releases?q=helm-chart&expanded=true
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: argocd
spec:
  project: default
  sources:
  - repoURL: https://charts.external-secrets.io
    chart: external-secrets
    targetRevision: "2.*"
    helm:
      releaseName: external-secrets
      valueFiles:
      - $repo/values/external-secrets.yaml
  - repoURL: https://github.com/kevinchanaka/kube-cluster-apps.git
    targetRevision: HEAD
    ref: repo
  syncPolicy:
    syncOptions:
    - ServerSideApply=true
    - CreateNamespace=true
  destination:
    namespace: external-secrets
    server: https://kubernetes.default.svc

---

# Releases: https://github.com/cert-manager/cert-manager/releases
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
spec:
  project: default
  sources:
  - repoURL: https://charts.jetstack.io
    chart: cert-manager
    targetRevision: "1.*"
    helm:
      releaseName: cert-manager
      valueFiles:
      - $repo/values/cert-manager.yaml
  - repoURL: https://github.com/kevinchanaka/kube-cluster-apps.git
    targetRevision: HEAD
    ref: repo
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
  destination:
    namespace: cert-manager
    server: https://kubernetes.default.svc

---

# Releases: https://github.com/metallb/metallb/releases?q=metallb-chart&expanded=true
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb
  namespace: argocd
spec:
  project: default
  sources:
  - repoURL: https://metallb.github.io/metallb
    chart: metallb
    targetRevision: "0.15.*"
    helm:
      releaseName: metallb
      valueFiles:
      - $repo/values/metallb.yaml
  - repoURL: https://github.com/kevinchanaka/kube-cluster-apps.git
    targetRevision: HEAD
    ref: repo
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
  destination:
    namespace: metallb-system
    server: https://kubernetes.default.svc

---

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: proxmox-csi-plugin
  namespace: argocd
spec:
  project: default
  sources:
  - repoURL: ghcr.io/sergelogvinov/charts
    chart: proxmox-csi-plugin
    targetRevision: "0.*"
    helm:
      releaseName: proxmox-csi-plugin
      valueFiles:
      - $repo/values/proxmox-csi-plugin.yaml
  - repoURL: https://github.com/kevinchanaka/kube-cluster-apps.git
    targetRevision: HEAD
    ref: repo
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
  destination:
    namespace: csi-proxmox
    server: https://kubernetes.default.svc


---

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack-crds
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/prometheus-community/helm-charts.git
    path: charts/kube-prometheus-stack/charts/crds/crds
    targetRevision: kube-prometheus-stack-82.10.5
    directory:
      recurse: true
  syncPolicy:
    syncOptions:
    - Replace=true
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc

---

# Releases: https://github.com/prometheus-community/helm-charts/pkgs/container/charts%2Fkube-prometheus-stack
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
spec:
  project: default
  sources:
  - repoURL: https://prometheus-community.github.io/helm-charts
    chart: kube-prometheus-stack
    targetRevision: 82.10.5
    helm:
      releaseName: kps
      skipCrds: true
      valueFiles:
      - $repo/values/kube-prometheus-stack.yaml
  - repoURL: https://github.com/kevinchanaka/kube-cluster-apps.git
    targetRevision: HEAD
    ref: repo
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc

---

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
spec:
  project: default
  sources:
  - repoURL: ghcr.io/traefik/helm
    chart: traefik
    targetRevision: "39.*"
    helm:
      releaseName: 
      valueFiles:
      - $repo/values/traefik.yaml
  - repoURL: https://github.com/kevinchanaka/kube-cluster-apps.git
    targetRevision: HEAD
    ref: repo
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
  destination:
    namespace: traefik 
    server: https://kubernetes.default.svc

---

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns
  namespace: argocd
spec:
  project: default
  sources:
  - repoURL: https://kubernetes-sigs.github.io/external-dns/
    chart: external-dns
    targetRevision: "1.*"
    helm:
      releaseName:
      valueFiles:
      - $repo/values/external-dns.yaml
  - repoURL: https://github.com/kevinchanaka/kube-cluster-apps.git
    targetRevision: HEAD
    ref: repo
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
  destination:
    namespace: default 
    server: https://kubernetes.default.svc
