apiVersion: apps/v1
kind: Deployment
metadata:
  name: minecraft-ozone-3
  namespace: default
  labels:
    app: minecraft-ozone-3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minecraft-ozone-3
  strategy:
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 0
  template:
    metadata:
      labels:
        app: minecraft-ozone-3
    spec:
      containers:
      - name: minecraft-ozone-3
        image: itzg/minecraft-server:java8-openj9
        stdin: true
        tty: true
        env:
        - name: TYPE
          value: "FORGE"
        - name: FORGE_INSTALLER
          value: "forge-1.12.2-14.23.5.2860.jar"
        - name: MEMORY
          value: "8G"
        - name: EULA
          value: "TRUE"
        - name: TUNE_NURSERY_SIZES
          value: "TRUE"
        - name: DEBUG
          value: "true"
        volumeMounts:
        - name: minecraft-data
          mountPath: /data
        ports:
        - containerPort: 25565
        resources:
          requests:
            memory: 8300Mi
            cpu: "2"
      volumes:
      - name: minecraft-data
        persistentVolumeClaim:
          claimName: minecraft-ozone-3

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minecraft-ozone-3
  namespace: default
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi

---

apiVersion: v1
kind: Service
metadata:
  name: minecraft-ozone-3
  namespace: default
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.50.162
  selector:
    app: minecraft-ozone-3
  ports:
    - protocol: TCP
      port: 25565
