apiVersion: apps/v1
kind: Deployment
metadata:
  name: ubuntu
  namespace: default
  labels:
    app: ubuntu
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ubuntu
  template:
    metadata:
      labels:
        app: ubuntu
    spec:
      containers:
      - name: ubuntu
        image: ubuntu
        env:
        - name: DEBIAN_FRONTEND
          value: noninteractive
        command: ["/bin/bash"]
        args:
        - -c
        - >
          apt-get update;
          apt-get install -y dnsutils curl net-tools tcpdump;
          sleep infinity;
