# Values file for cert-manager helm chart
# Install CRDs manually before installing chart
# https://artifacthub.io/packages/helm/cert-manager/cert-manager
# helm upgrade -i -n cert-manager -f cert-manager.yaml 
# helm install -n cert-manager -f cert-manager.yaml cert-manager jetstack/cert-manager --version v1.6.0

cert-manager:
  installCRDs: true

  prometheus:
    enabled: true
    servicemonitor: 
      enabled: true
      namespace: monitoring

  webhook:
    timeoutSeconds: 4
