apiVersion: v2
name: fluent-bit
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: "1.0"
dependencies:
- name: fluent-bit
  version: 0.20.8
  repository: https://fluent.github.io/helm-charts