# Values file for fluent-bit
# https://github.com/fluent/helm-charts/blob/main/charts/fluent-bit/values.yaml
# Assumes fluent-bit configmap already exists
# Using fluent-bit container for loki
# helm upgrade -i -n monitoring -f fluent-bit.yaml fluent-bit fluent/fluent-bit

fluent-bit:
  image: 
    repository: grafana/fluent-bit-plugin-loki
    pullPolicy: Always
    tag: 2.1.0-amd64

  existingConfigMap: fluent-bit

  volumeMounts:
  - name: config
    mountPath: /fluent-bit/etc

  tolerations:
  - key: node-role.kubernetes.io/master
    operator: Exists
    effect: "NoSchedule"

  resources:
    requests:
      cpu: 100m
      memory: 128Mi
